baseURL = 'https://flashburger.github.io/RoQZoo-hugo-blog/'
languageCode = 'ko-kr'
title = 'æ—¥å¸¸é›œè¨˜'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false 
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "ì†Œê°œê¸€ ğŸ‘‹"
  Content = "ì €ì ì†Œê°œ ì…ë‹ˆë‹¤. ì—¬ê¸°ì— ì—°ë½ì²˜"
  

[[menu.main]]
  name = "Archive"
  url = "/archives/"
  weight = 10

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 30



  # ê¸°ì¡´ [params] ì„¹ì…˜ ì•„ë˜ì— ì¶”ê°€
[[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/your_username"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/your_username"

[[params.socialIcons]]
  name = "threads"
  url = "https://threads.net/@your_username"